# Generated by Django 4.2 on 2023-04-23 05:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('petshopapp', '0015_delete_procedimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id_petshop', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_dono', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('nome_do_pet', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=12)),
                ('email', models.EmailField(default=uuid.uuid4, max_length=50)),
            ],
        ),
    ]
